### ISSUE TITLE
Update Sheet Section and Subsection styling

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#269]
Currently sections and subsections on designs don't have significant impact and seem to meld in with the rest of the form. These should be called out a bit more and made more definitive.
`sheets.scss`

```scss
.section {
  font-weight: 600;
  margin-top: 50px;
  border-bottom: 1px solid #333;
  padding-bottom: 9.5px;
}
.subsection {
  ...
}
```
